# Generated by Django 5.2.5 on 2025-10-20 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0001_initial'),
        ('venturetypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventureaccount',
            name='venture_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventures', to='venturetypes.venturetype'),
        ),
    ]
