# Generated by Django 5.2.5 on 2025-10-18 07:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savings', '0002_rename_user_savingsaccount_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_method', models.CharField(choices=[('Mpesa', 'Mpesa'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=100)),
                ('transaction_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Processing', max_length=100)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('identity', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('savings_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='savings.savingsaccount')),
                ('withdrawn_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savings Withdrawal',
                'verbose_name_plural': 'Savings Withdrawals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['savings_account', 'created_at'], name='savingswith_savings_f8ed78_idx'), models.Index(fields=['withdrawn_by', 'created_at'], name='savingswith_withdra_831298_idx'), models.Index(fields=['reference'], name='savingswith_referen_27728f_idx')],
            },
        ),
    ]
