# Generated by Django 5.2.5 on 2025-10-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingswithdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingswithdrawal',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Processing', max_length=100),
        ),
    ]
