# Generated by Django 5.2.5 on 2025-11-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='calculation_mode',
            field=models.CharField(choices=[('fixed_term', 'Fixed Term'), ('fixed_payment', 'Fixed Payment')], default='fixed_term', max_length=20),
            preserve_default=False,
        ),
    ]
