# Generated by Django 5.2.5 on 2025-11-15 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplications', '0002_alter_loanapplication_calculation_mode'),
        ('loans', '0004_remove_loanaccount_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='loan_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='loans.loanaccount'),
        ),
    ]
