# Generated by Django 5.2.5 on 2025-11-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplications', '0004_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Ready for Submission', 'Ready for Submission'), ('Ready for Review', 'Ready for Review'), ('Submitted', 'Submitted'), ('Ammended', 'Ammended'), ('Reviewed', 'Reviewed'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30),
        ),
    ]
