# Generated by Django 5.2.5 on 2025-11-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplications', '0004_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready for Amendment', 'Ready for Amendment'), ('Amended', 'Amended'), ('In Progress', 'In Progress'), ('Ready for Submission', 'Ready for Submission'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], default='Ready for Amendment', max_length=30),
        ),
    ]
