# Generated by Django 5.2.5 on 2026-02-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplications', '0005_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='amendment_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
