# Generated by Django 5.2.5 on 2025-09-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsaccount',
            old_name='user',
            new_name='member',
        ),
    ]
