# Generated by Django 5.2.5 on 2026-02-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feetypes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feetype',
            name='standard_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
