# Generated by Django 5.2.5 on 2026-02-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feetypes', '0002_feetype_is_active_feetype_standard_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='is_income',
            field=models.BooleanField(default=False),
        ),
    ]
