# Generated by Django 5.2.5 on 2026-02-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feetypes', '0003_feetype_is_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='is_asset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feetype',
            name='is_equity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feetype',
            name='is_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feetype',
            name='is_liability',
            field=models.BooleanField(default=False),
        ),
    ]
