# Generated by Django 5.2.5 on 2025-11-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guaranteerequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guaranteerequest',
            unique_together=set(),
        ),
    ]
