# Generated by Django 5.2.5 on 2026-02-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guaranteerequests', '0002_alter_guaranteerequest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteerequest',
            name='guaranteed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
