# Generated by Django 5.2.5 on 2026-02-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guaranteerequests', '0003_alter_guaranteerequest_guaranteed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='guaranteerequest',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining guaranteed amount after repayments', max_digits=15, null=True),
        ),
    ]
