# Generated by Django 5.2.5 on 2025-09-21 02:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savings', '0002_rename_user_savingsaccount_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='Amount must be greater than 0')])),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('payment_method', models.CharField(choices=[('Mpesa', 'Mpesa'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Mobile Banking', 'Mobile Banking'), ('Standing Order', 'Standing Order')], max_length=100)),
                ('deposit_type', models.CharField(choices=[('Opening Balance', 'Opening Balance'), ('Payroll Deduction', 'Payroll Deduction'), ('Individual Deposit', 'Individual Deposit'), ('Group Deposit', 'Group Deposit'), ('Dividend Deposit', 'Dividend Deposit'), ('Other', 'Other')], default='Individual Deposit', max_length=100)),
                ('transaction_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('identity', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('deposited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='savings_deposits', to=settings.AUTH_USER_MODEL)),
                ('savings_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='savings.savingsaccount')),
            ],
            options={
                'verbose_name': 'Savings Deposit',
                'verbose_name_plural': 'Savings Deposits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['savings_account', 'created_at'], name='savingsdepo_savings_7c6340_idx'), models.Index(fields=['deposited_by', 'created_at'], name='savingsdepo_deposit_efa7ae_idx'), models.Index(fields=['reference'], name='savingsdepo_referen_b0a2d8_idx')],
            },
        ),
    ]
