# Generated by Django 5.2.5 on 2025-09-30 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_rename_user_savingsaccount_member'),
        ('savingsdeposits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsdeposit',
            name='savings_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='savings.savingsaccount'),
        ),
    ]
