# Generated by Django 5.2.5 on 2025-10-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsdeposits', '0002_alter_savingsdeposit_savings_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsdeposit',
            name='payment_method',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Mobile Banking', 'Mobile Banking'), ('Standing Order', 'Standing Order')], default='Cash', max_length=100),
        ),
    ]
