# Generated by Django 5.2.5 on 2025-10-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsdeposits', '0003_alter_savingsdeposit_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsdeposit',
            name='deposit_type',
            field=models.CharField(choices=[('Opening Balance', 'Opening Balance'), ('Payroll Deduction', 'Payroll Deduction'), ('Individual Deposit', 'Individual Deposit'), ('Dividend Deposit', 'Dividend Deposit'), ('Other', 'Other')], default='Individual Deposit', max_length=100),
        ),
    ]
