# Generated by Django 5.2.5 on 2025-11-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsdeposits', '0004_alter_savingsdeposit_deposit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsdeposit',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=100),
        ),
    ]
