# Generated by Django 5.2.5 on 2025-09-02 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_no',
            new_name='id_number',
        ),
    ]
