# Generated by Django 5.2.5 on 2025-09-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_id_no_user_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='member_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
