# Generated by Django 5.2.5 on 2025-09-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_middle_name_alter_user_member_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
