# Generated by Django 5.2.5 on 2025-11-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextofkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextofkin',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
            preserve_default=False,
        ),
    ]
