# Generated by Django 5.2.5 on 2025-09-30 18:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0002_alter_loanaccount_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='Amount must be greater than 0')])),
                ('payment_method', models.CharField(choices=[('Mpesa', 'Mpesa'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Mobile Banking', 'Mobile Banking'), ('Standing Order', 'Standing Order')], max_length=100)),
                ('repayment_type', models.CharField(choices=[('Regular Repayment', 'Regular Repayment'), ('Payroll Deduction', 'Payroll Deduction'), ('Interest Payment', 'Interest Payment'), ('Individual Settlement', 'Individual Settlement'), ('Early Settlement', 'Early Settlement'), ('Partial Payment', 'Partial Payment'), ('Other', 'Other')], default='Regular Repayment', max_length=100)),
                ('transaction_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=100)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('identity', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loans.loanaccount')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Repayment',
                'verbose_name_plural': 'Loan Repayments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['loan_account', 'created_at'], name='loanrepayme_loan_ac_5e8643_idx'), models.Index(fields=['paid_by', 'created_at'], name='loanrepayme_paid_by_44cb72_idx'), models.Index(fields=['transaction_status'], name='loanrepayme_transac_0607a1_idx')],
            },
        ),
    ]
