# Generated by Django 5.2.5 on 2025-09-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingstypes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingstype',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
