# Generated by Django 5.2.5 on 2026-02-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingstypes', '0002_savingstype_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingstype',
            name='is_guaranteed',
            field=models.BooleanField(default=False),
        ),
    ]
