# Generated by Django 5.2.5 on 2025-10-20 07:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentureDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('deposited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venture_deposits', to=settings.AUTH_USER_MODEL)),
                ('venture_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='ventures.ventureaccount')),
            ],
            options={
                'verbose_name': 'Venture Deposit',
                'verbose_name_plural': 'Venture Deposits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['venture_account', 'created_at'], name='venturedepo_venture_b0bd1b_idx'), models.Index(fields=['reference'], name='venturedepo_referen_6865fe_idx')],
            },
        ),
    ]
