# Generated by Django 5.2.5 on 2025-10-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venturedeposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venturedeposit',
            name='identity',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
