# Generated by Django 5.2.5 on 2025-10-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venturedeposits', '0002_venturedeposit_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venturedeposit',
            name='identity',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
