# Generated by Django 5.2.5 on 2025-11-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loanaccount_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanaccount',
            old_name='user',
            new_name='member',
        ),
    ]
