# Generated by Django 5.2.5 on 2025-11-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_rename_user_loanaccount_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanaccount',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='loan_amount',
        ),
    ]
