# Generated by Django 5.2.5 on 2025-10-20 08:09

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventures', '0002_alter_ventureaccount_venture_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenturePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='Amount must be greater than 0')])),
                ('payment_method', models.CharField(choices=[('Mpesa', 'Mpesa'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Mobile Banking', 'Mobile Banking'), ('Standing Order', 'Standing Order')], default='Cash', max_length=100)),
                ('transaction_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=100)),
                ('payment_type', models.CharField(choices=[('Regular Payment', 'Regular Payment'), ('Payroll Deduction', 'Payroll Deduction'), ('Interest Payment', 'Interest Payment'), ('Individual Settlement', 'Individual Settlement'), ('Early Settlement', 'Early Settlement'), ('Partial Payment', 'Partial Payment'), ('Other', 'Other')], default='Individual Settlement', max_length=100)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('identity', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venture_payments', to=settings.AUTH_USER_MODEL)),
                ('venture_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ventures.ventureaccount')),
            ],
            options={
                'verbose_name': 'Venture Payment',
                'verbose_name_plural': 'Venture Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
