# Generated by Django 5.2.5 on 2025-09-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loantypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loantype',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loan Type', 'verbose_name_plural': 'Loan Types'},
        ),
        migrations.AddField(
            model_name='loantype',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
