# Generated by Django 5.2.5 on 2025-10-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loantypes', '0002_alter_loantype_options_loantype_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='system_calculates_interest',
            field=models.BooleanField(default=False),
        ),
    ]
