# Generated by Django 5.2.5 on 2025-11-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loantypes', '0003_loantype_system_calculates_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantype',
            name='system_calculates_interest',
        ),
    ]
