# Generated by Django 5.2.5 on 2026-02-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberfees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberfee',
            name='is_active',
        ),
    ]
