# Generated by Django 5.2.5 on 2026-02-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberfees', '0002_remove_memberfee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberfee',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
