# Generated by Django 5.2.5 on 2025-10-24 19:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0002_alter_loanaccount_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TamarindLoanInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamarind_interests', to='loans.loanaccount')),
            ],
            options={
                'verbose_name': 'Tamarind Loan Interest',
                'verbose_name_plural': 'Tamarind Loan Interests',
                'ordering': ['-created_at'],
            },
        ),
    ]
