# Generated by Django 5.2.5 on 2025-10-24 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanintereststamarind', '0001_initial'),
        ('loans', '0002_alter_loanaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamarindloaninterest',
            name='loan_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_interests', to='loans.loanaccount'),
        ),
    ]
